// Publications
export const GET_ALL_PUBLICATIONS = 'GET_ALL_PUBLICATIONS';
export const GET_FILTERED_PUBLICATIONS = 'GET_FILTERED_PUBLICATIONS';
export const PUBLICATIONS_ERROR = 'PUBLICATIONS_ERROR';
