// Publications
export const GET_ALL_PUBLICATIONS = 'GET_ALL_PUBLICATIONS';
export const GET_FILTERED_PUBLICATIONS = 'GET_FILTERED_PUBLICATIONS';
export const PUBLICATIONS_ERROR = 'PUBLICATIONS_ERROR';

// Single Publication
export const GET_SINGLE_PUBLICATION = 'GET_SINGLE_PUBLICATION';
export const SINGLE_PUBLICATION_ERROR = 'SINGLE_PUBLICATION_ERROR';
export const RESET_SINGLE_PUBLICATION_LOADING =
  'RESET_SINGLE_PUBLICATION_LOADING';
